---

- hosts: all
  become: true
  tasks: 
    - name: Install python pip
      yum: 
        name: python-pip
        state: present
        
    - name: Install docker-py python
      pip: 
        name: docker.py
        state: present
        
    - name: Start container
      docker_container: 
        name: 12981406
        image: 12981406/testfile:0.0.1
        state: started
        published_ports: 
                  -0.0.0.0:8080:8080
    
